USE [master]
GO

/****** Object:  Database [Assignment_PRJ_CoKyAi]    Script Date: 11/8/2022 10:08:16 PM ******/
CREATE DATABASE [Assignment_PRJ_CoKyAi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment_PRJ_CoKyAi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Assignment_PRJ_CoKyAi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assignment_PRJ_CoKyAi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Assignment_PRJ_CoKyAi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment_PRJ_CoKyAi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET RECOVERY FULL 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET  MULTI_USER 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Assignment_PRJ_CoKyAi] SET  READ_WRITE 
GO

